import { v4 as id } from "uuid";

const des = `Introducing our adorable and comfortable infant shirt, crafted from premium-quality cotton for ultimate coziness. The envelope neck and short sleeves provide easy dressing and freedom of movement. With vibrant colors and a captivating design, this shirt celebrates your baby's unique personality. It's cute, practical with durable stitching, and machine-washable. Available in sizes for newborns to 24 months, it's perfect for any occasion or as a heartfelt gift. Dress your little one in pure cuteness and let their personality shine bright!`;
const additionalInfo = [
  {
    title: "Materials",
    description: `This adorable and comfortable infant shirt is carefully crafted from the finest, premium-quality cotton fabric. We understand the importance of providing a garment that is soft, breathable, and gentle against your baby's sensitive skin. The cotton fabric used in this shirt has been thoughtfully selected to ensure utmost comfort and safety for your little one. With its superior quality, this shirt offers a cozy and snug fit that will keep your baby feeling comfortable and happy throughout the day.`,
  },
  {
    title: "Care Instructions",
    description: `To care for this infant shirt, machine wash in cold water with like colors on a gentle cycle. Use a mild detergent and avoid bleach or fabric softeners. Tumble dry on low heat or line dry in the shade. Iron on low if needed, avoiding prints or embellishments. Following these instructions will keep the shirt looking great and ensure its longevity.`,
  },
];

export default [
  {
    productId: 1,
    skuId: "00001",
    images: ["./productimages/Product1.png"],
    alt: "a baby top shirt",
    name: "i'm a product",
    key: id(),
    ribbon: "NEW",
    price: 19.99,
    discountedPrice: 19.99,
    formattedPrice: "$19.99",
    formattedDiscountedPrice: "$19.99",
    options: {
      colors: [
        {
          color: "Green",
          value: "#86AD91",
        },
      ],
      sizes: ["Free Size"],
    },
    description: des,
    additionalInfo,
  },
  {
    productId: 2,
    skuId: "00002",
    images: ["./productimages/Product2.png"],
    alt: "a baby top shirt",
    name: "i'm a product",
    key: id(),
    ribbon: "NEW",
    price: 19.99,
    discountedPrice: 19.99,
    formattedPrice: "$19.99",
    formattedDiscountedPrice: "$19.99",
    options: {
      colors: [
        {
          color: "Peach",
          value: "#F9BB9C",
        },
      ],
      sizes: ["Free Size"],
    },
    description: des,
    additionalInfo,
  },
  {
    productId: 3,
    skuId: "00003",
    images: ["./productimages/Product3.png"],
    alt: "a baby top shirt",
    name: "i'm a product",
    key: id(),
    ribbon: "SALE",
    price: 19.99,
    discountedPrice: 17.99,
    formattedPrice: "$19.99",
    formattedDiscountedPrice: "$17.99",
    options: {
      colors: [
        {
          color: "Blue",
          value: "#458FFF",
        },
      ],
      sizes: ["Free Size"],
    },
    description: des,
    additionalInfo,
  },
  {
    productId: 4,
    skuId: "00004",
    images: ["./productimages/Product4.png"],
    alt: "a baby top shirt",
    name: "i'm a product",
    key: id(),
    price: 19.99,
    discountedPrice: 19.99,
    formattedPrice: "$19.99",
    formattedDiscountedPrice: "$19.99",
    options: {
      colors: [
        {
          color: "Peach",
          value: "#F9BB9C",
        },
      ],
      sizes: ["Free Size"],
    },
    description: des,
    additionalInfo,
  },
  {
    productId: 5,
    skuId: "00005",
    images: ["./productimages/Product5.png"],
    alt: "a baby top shirt",
    name: "i'm a product",
    key: id(),
    price: 19.99,
    ribbon: "NEW",
    discountedPrice: 19.99,
    formattedPrice: "$19.99",
    formattedDiscountedPrice: "$19.99",
    options: {
      colors: [
        {
          color: "White",
          value: "ffffff",
        },
      ],
      sizes: ["Free Size"],
    },
    description: des,
    additionalInfo,
  },
  {
    productId: 6,
    skuId: "00006",
    images: ["./productimages/Product6.png"],
    alt: "a baby top shirt",
    name: "i'm a product",
    key: id(),
    ribbon: "SALE",
    price: 19.99,
    discountedPrice: 17.99,
    formattedPrice: "$19.99",
    formattedDiscountedPrice: "$17.99",
    options: {
      colors: [
        {
          color: "White",
          value: "ffffff",
        },
      ],
      sizes: ["Free Size"],
    },
    description: des,
    additionalInfo,
  },
  {
    productId: 7,
    skuId: "00007",
    images: ["./productimages/Product7.png"],
    alt: "a baby top shirt",
    name: "i'm a product",
    key: id(),
    price: 19.99,
    discountedPrice: 19.99,
    formattedPrice: "$19.99",
    formattedDiscountedPrice: "$19.99",
    options: {
      colors: [
        {
          color: "Blue",
          value: "#458FFF",
        },
      ],
      sizes: ["Free Size"],
    },
    additionalInfo,
  },
  {
    productId: 8,
    skuId: "00008",
    images: ["./productimages/Product8.png"],
    alt: "a baby top shirt",
    name: "i'm a product",
    key: id(),
    ribbon: "SALE",
    price: 19.99,
    discountedPrice: 17.99,
    formattedPrice: "$19.99",
    formattedDiscountedPrice: "$17.99",
    options: {
      colors: [
        {
          color: "Teracotta",
          value: "#CD7551",
        },
      ],
      sizes: ["Free Size"],
    },
    description: des,
    additionalInfo,
  },
  {
    productId: 9,
    skuId: "00009",
    images: ["./productimages/Product9.png"],
    alt: "a baby top shirt",
    name: "i'm a product",
    key: id(),
    price: 19.99,
    discountedPrice: 19.99,
    formattedPrice: "$19.99",
    formattedDiscountedPrice: "$19.99",
    options: {
      colors: [
        {
          color: "White",
          value: "#ffffff",
        },
      ],
      sizes: ["Free Size"],
    },
    description: des,
    additionalInfo,
  },
  {
    productId: 10,
    skuId: "00010",
    images: ["./productimages/Product10.png"],
    alt: "a baby top shirt",
    name: "i'm a product",
    key: id(),
    ribbon: "SALE",
    price: 19.99,
    discountedPrice: 17.99,
    formattedPrice: "$19.99",
    formattedDiscountedPrice: "$17.99",
    options: {
      colors: [
        {
          color: "White",
          value: "#ffffff",
        },
      ],
      sizes: ["Free Size"],
    },
    description: des,
    additionalInfo,
  },
  {
    productId: 11,
    skuId: "000011",
    images: ["./productimages/Product11.png"],
    alt: "a baby top shirt",
    name: "i'm a product",
    key: id(),
    price: 19.99,
    discountedPrice: 19.99,
    formattedPrice: "$19.99",
    formattedDiscountedPrice: "$19.99",
    options: {
      colors: [
        {
          color: "Blue",
          value: "#458FFF",
        },
      ],
      sizes: ["Free Size"],
    },
    description: des,
    additionalInfo,
  },
  {
    productId: 12,
    skuId: "000012",
    images: ["./productimages/Product12.png"],
    alt: "a baby top shirt",
    name: "i'm a product",
    key: id(),
    ribbon: "NEW",
    price: 19.99,
    discountedPrice: 19.99,
    formattedPrice: "$19.99",
    formattedDiscountedPrice: "$19.99",
    options: {
      colors: [
        {
          color: "Blue",
          value: "#458FFF",
        },
      ],
      sizes: ["Free Size"],
    },
    description: des,
    additionalInfo,
  },
];
